project:
  type: website
  output-dir: docs

website:
  title: "Study-SUSC"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - note/part_01.qmd
      - note/part_02.qmd
      - section: "예제"
        contents:
          - practice/practice01.ipynb
          - practice/practice02.ipynb
          - practice/practice03.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  # pdf:
  #   documentclass: scrreprt
  #   papersize: a4
  #   toc: true
  #   toc-depth: 2
  #   number-sections: true
  #   colorlinks: true
  #   include-in-header: 
  #     text: |
  #       \usepackage{kotex}
