project:
  type: website
  output-dir: docs

website:
  title: "Study-SUSC"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - note/part_01a.qmd
      - section: "예제"
        contents:
          - practice/practice01.ipynb
          - practice/practice02.ipynb


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



