---
title: "Study-SUSC"
---

## 추천시스템

이번 스터디에선 추천시스템에 대한 정의를 일반적[^1]이고 학술적인 형태가 아닌 조작적으로 정의하도록 하겠습니다. 조작적 정의이기 때문에 어딘가서 아래와 같은 `정의`를 사용하실 때 주의하세요. 합의되지 않았습니다. 단지 "스터디"에 필요한 정의일 뿐입니다.

[^1]: https://files.grouplens.org/papers/Konstan-Summer-01

> [정의] 추천시스템은 여러 가능성 가운데, 몇가지 가치 있는 것을 선별, 그 중에서 $n$개를 선정하는 의사 결정을 도와주는 시스템 또는 방법

- 여러 가능성 가운데, 몇가지 가치 있는 것을 선별 
    - 가능성을 정의하는 기준에 따라 다양한 방법을 활용할 수 있는데, 단순한 방법(Top-K)에서, 복잡한 방법 등 가능성을 계산만 할 수 있다면 어떤 것도 가능

- 그 중에서 $n$개를 선정
    - 목적에 맞춰 알고리즘을 적절하게 선택해서 사용
    
- 의사 결정을 도와주는
    - 사용자의 의사 결정 과정에서 큰 영향력을 발휘하는게 목표로 선택한 항목을 사용자가 실제로 활용하는 것을 최종 목표로 함

### 데이터분석에 대한 필요성

추천시스템의 기본적인 아이디어는 "다양한 데이터 소스를 활용해 고객의 관심을 추론"하는 것입니다. 과거 관심사와 성향이 미래 선택에 대한 좋은 방향성을 제시해주는 경우가 많기 때문에 추천에 관련된 분석은 흔히 사용자와 아이템 간의 "과거"의 상호작용에 기반한다고 가정하고 있습니다. 예외적으로 지식 기반 추천 시스템의 경우인데, 이때는 사용자의 과거 이력보다는 사용자가 지정한 요구 사항에 따라 제안됩니다. 따라서 모든 추천시스템의 시작은 "과거 데이터"와 "사용자 데이터"의 의존성을 가정하기 때문에, 해당 데이터를 다루는 것에서 시작됩니다.

### 알고리즘에 대한 필요성

1990년대 인터넷의 발전과 함께 다양한 것이 정보화 되고 거기에 접근할 수 있게 되며 여러 후보가운데 가치 있는것을 선정하는 기술이 중요해졌습니다. 제록스 팔로알토 연구소의 연구자 골드버그(Goldberg)는 대표적인 추천 알고리즘의 하나인 협조필터링[^2]을 처음으로 적용한 추천시스템을 제안하였습니다. 이 알고리즘은 전자 메일 중에서 유익한 메일을 선택하는 것으로, 필터 처리만으로는 유익한 메일을 찾아내는 것이 어렵기 때문에 협조 필터링을 사용한 메일 스코어링(scoring)을 계산하는 것이 핵심 골자입니다.

[^2]: https://dl.acm.org/doi/10.1145/138859.138867

대부분의 추천시스템은 이런 형태의 알고리즘을 필요로 합니다. 그리고 많은 문제는 주어진 알고리즘을 그대로 활용하기 보다는 적당한 수준에서 변경(trade-off)를 필요로 합니다. 따라서 많은 알고리즘을 알면 좋지만, 가장 널리 사용되는 알고리즘을 활용하는 것도 중요합니다.

주어진 문제를 어떻게 해결할 것인가에 대해선 해당 문제를 해결하는 전문가의 몫이라 할 수 있습니다. 우리는 스터디를 진행하기 때문에 문제를 '잘' 해결하는 것에 주력을 하는 것이 아니라, 문제를 해결하는 것에 집중하도록 하겠습니다. 그래서 가능하다면 널리 사용되는 알고리즘을 활용하는 방향으로 진행하도록 하겠습니다.

### 추천시스템의 종류

일반적으로 추천 시스템은 입력-프로세스-출력의 3가지 요소로 정리할 수 있습니다. 당연한 이야기처럼 느껴지겠지만, 이런 분류를 이해하지 못하면 전혀 어뚱한 시스템을 설계하게 됩니다.

- 입력
    - 콘텐츠 -> 내용 기반 필터링(CBF)
    - 행위 -> 협조 필터링(CF) -> 콜드 스타트 문제

- 프로세스
    - 경향성 -> Top-K 
    - 연관성 -> 유사도 -> {협조 or 내용}
    - 개인화 -> 협조 필터

- 출력
    - 빈도적 -> 특징 시점
    - 즉시적 -> 사이드바
    - 비즉시적 -> 메일, 메시지

`[연습문제]` 추천시스템이 검색시스템과 어떤 차이가 있나요? 
