---
title: "추천 시스템 스터디 Part2"
author: "Sangkon Han"
---

## 데이터분석에 대한 필요성

추천시스템의 기본적인 아이디어는 "다양한 데이터 소스를 활용해 고객의 관심을 추론"하는 것입니다. 과거 관심사와 성향이 미래 선택에 대한 좋은 방향성을 제시해주는 경우가 많기 때문에 추천에 관련된 분석은 흔히 사용자와 아이템 간의 "과거"의 상호작용에 기반한다고 가정하고 있습니다. 예외적으로 지식 기반 추천 시스템의 경우인데, 이때는 사용자의 과거 이력보다는 사용자가 지정한 요구 사항에 따라 제안됩니다. 

모든 추천시스템의 시작은 "과거 데이터"와 "사용자 데이터"의 의존성을 가정하기 때문에, 해당 데이터를 다루는 것에서 시작됩니다.

## 알고리즘에 대한 필요성

1990년대 인터넷의 발전과 함께 다양한 것이 정보화 되고 거기에 접근할 수 있게 되면서 여러 후보 가운데 가치 있는것을 선정하는 기술이 중요해졌습니다. 제록스 팔로알토 연구소의 연구자 골드버그(Goldberg)는 대표적인 추천 알고리즘의 하나인 협조필터링[^2]을 처음으로 적용한 추천시스템을 제안하였습니다. 이 알고리즘은 전자 메일 중에서 유익한 메일을 선택하는 것으로, 필터 처리만으로는 유익한 메일을 찾아내는 것이 어렵기 때문에 협조 필터링을 사용한 메일 스코어링(scoring)을 계산하는 것이 핵심 골자입니다.

[^2]: https://dl.acm.org/doi/10.1145/138859.138867

### 모든 것이 계산이고, 우리느 그러한 계산을 알고리즘으로 부르기로 하였다.

대부분의 추천시스템은 이런 형태의 알고리즘을 필요로 합니다. 그리고 많은 문제는 주어진 알고리즘을 그대로 활용하기 보다는 적당한 수준에서 변경(`trade-off`)를 필요로 합니다. 따라서 많은 알고리즘을 알면 좋지만, 가장 널리 사용되는 알고리즘을 활용하는 것도 중요합니다. 일반적으로 계산 알고리즘을 변용하는 과정에서 발생하는 몇가지 문제를 쉽게 예상하고 해결하기 위해서 입니다. 

주어진 문제를 어떻게 해결할 것인가에 대해선 해당 문제를 해결하는 전문가의 몫이라 할 수 있습니다. 그리고 이런 자유도가 주어졌을 때, 전문가의 선택을 가장 많이 받은 것들을 알아둘 필요가 있습니다. 모든 일은 협업이니까요.

아쉽게도 우리는 스터디를 진행하기 때문에 문제를 '잘' 해결하는 것에 주력을 하는 것이 아니라, 문제를 해결하는 것에 집중하도록 하겠습니다. 그래서 가능하다면 널리 사용되는 알고리즘을 활용하는 방향으로 진행하도록 하겠습니다.

## 추천시스템의 종류

일반적으로 추천 시스템은 `입력-프로세스-출력`의 3가지 요소로 정리할 수 있습니다. 당연한 이야기처럼 느껴지겠지만, 이런 분류를 이해하지 못하면 전혀 어뚱한 시스템을 설계하게 됩니다.

- 입력
    - 콘텐츠 => 내용 기반 필터링(CBF)
    - 행위 => 협조 필터링(CF)

- 프로세스
    - 경향성 => Top-$K$
        - <https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=a401596b7c337afefe0ea228ef9cd4908429b43a>
        - <https://link.springer.com/content/pdf/10.1007/s10115-007-0114-2.pdf>
    - 연관성 => 유사도
    - 개인화 => 협조 필터

- 출력
    - 빈도적 => 특징 시점
    - 즉시적 => 사이드바
    - 비즉시적 => 메일, 메시지

`[연습문제]` 추천시스템이 검색시스템과 어떤 차이가 있나요?

추천 시스템은 사용자에게 적절한 선택지를 제안하는 데 중점을 두고, 검색 시스템은 사용자가 요청한 정보를 정확하게 찾는 데 중점을 둡니다.

- 사용자 의도와 입력
    - 추천 시스템: 사용자 입력이 명확하지 않거나 없습니다. 시스템은 사용자의 과거 행동, 선호도, 인구 통계학적 정보 등을 기반으로 적절한 항목을 예측하고 제안합니다.
    - 검색 시스템: 사용자 입력이 명확합니다. 사용자가 특정한 정보를 찾기 위해 키워드나 문장을 입력하면, 시스템은 그에 맞는 결과를 반환합니다.

- 데이터 처리와 알고리즘
    - 추천 시스템: 협업 필터링, 콘텐츠 기반 필터링, 하이브리드 방식 등 다양한 알고리즘을 사용하여 개인화된 추천을 제공합니다. 대규모 데이터 분석과 사용자 행동 패턴을 학습하여 정확도를 높입니다.
    - 검색 시스템: 검색어와 관련된 문서를 찾기 위해 인덱싱된 데이터를 검색합니다. 주로 TF-IDF, PageRank와 같은 알고리즘을 사용하여 관련성을 판단합니다.

- 결과의 성격
    - 추천 시스템: 사용자가 명확하게 요청하지 않은 항목들을 제안합니다. 예를 들어, 사용자가 어떤 영화를 볼지 모르고 있을 때 관련 영화를 추천합니다.
    - 검색 시스템: 사용자가 명확하게 요청한 정보를 제공합니다. 예를 들어, 사용자가 특정 영화의 정보를 검색하면 그 영화에 대한 구체적인 결과를 반환합니다.

- <https://www.sciencedirect.com/science/article/pii/S1110866515000341#s0165>

## 추천시스템 구성
### 핵심 구성 요소 '사용자와 아이템'
- 사용자
    - 서비스를 사용하는 사람
-아이템
    - 서비스에서 판매하는 물품
    - 혹은 다른 사용자

[가정] 서비스가 성장하면 사용자/아이템도 함께 성장
    - 사용자는 성장
        - 사용자가 갑자기 검색을 하지 않음
    - 아이템은 거대해짐
        - 검색 결과가 많아짐

### 추천시스템을 바라보는 관점
추천시스템은 하나의 거대한 매칭(matching) 문제로 간주할 필요가 있음
- 어떻게 매칭할 것인가?
    - Top-K
    - Last-K
    - C.F
    - Order
- 부가 정보
    - 아이템 분류 체계
    - 사용자 프로파일
        - 개인정보(성별, 연령)
        - 아이템 정보(관심, 분류, 태그)
    - 기준
        - 클릭, 매출, 소비, 평점

## 추천시스템 알고리즘

### 내용(content) 기반(아이템 기반)

내용기반 필터링은 사용자가 어떤 내용의 아이템을 좋아하는지 나타내는 사용자 프로필과 아이템의 다양한 성질을 나타내는 특징을 추출한 아이템 특징과의 일치도 즉, 유사도를 계산함으로써 좋아할 만한 아이템을 사용자에게 추천하는 알고리즘입니다.

- 비슷한 아이템을 기반으로 추천
- 사용자의 선호도를 나타내는 사용자 프로필 획득 방법은 크게 2가지
    - 사용자의 과거 행동 이력에 기반해 사용자 프로필을 작성하는 간접 지정형
    - 사용자에게 자신이 선호하는 아이템의 특징을 명시적으로 지정하도록하는 직접 지정형

### 협조(collaborative) 기반

협조 필터링은 자신과 선호도가 비슷한 사용자의 과거 행동을 기반으로 얻어진 기호 경향을 활용하여 추천하는 알고리즘입니다. 협조 필터링은 메모리 기반 방법과 모델 기반 방법의 2가지로 나뉩니다. 

메모리기반 방법은 추천받을 사용자와 선호도가 비슷한 사용자에 착안하여 추천을 수행하는 사용자-사용자 메모리 기반 방법과 추천받을 사용자가 선호하는 아이템과 비슷한 아이템에 착안하여 추천하는 아이템-아이템 메모리 기반 방법이 있습니다.

협조필터링에서는 서비스내 다른사용자의 과거 행동이력 등으로부터 선호도 경향을 추정하여 추천에 사용했습니다. 이렇게 사용자로부터 얻은 아이템에 대한 선호도 정보를 기호 데이터(preference data)라 부릅니다. 기호 데이터를 획득하는 방법은 크게 명시적 피드백(explicit feedback)과 암묵적 피드백(implicit feedback)으로 나눌 수 있습니다.

수집한 기호데이터 등에 기반해 사용자가 해당 아이템의 선호도 정도를 정량적으로 나타낸 것
을 평가값이라 합니다. 그리고그 평갓값을 성분으로하는 사용자 $\times$ 아이템의 행렬을 평갓
값 행렬(rating matrix)이라고 합니다.

#### 모델 기반 방법 알고리즘개요

협조필터링 중에서도 모델 기반 방법은 이미 알고 있는 데이터의 규칙성을 학습한 모델을 미리 만들어둠으로써 모르는 아이템의 평갓값을 예측하여 추천하는 방법이었습니다. 예측에 사용하는 모델에는 클러스터링을 사용한 모델이나 회귀 문제 및 분류 문제로 평갓값을 직접 예측하는 토픽 모델(Topic Model)을 사용한 모델이나 행렬 분해(Factorization)를 사용한 모델 등 다양한 모델이 존재합니다.

평갓값을 회귀 문제나 분류 문제로 직접 예측하는 모델에서는 예를 들어 선형 회귀 등의 회귀모델을 사용해 과거 사용자로부터 얻은 아이템의 평갓값 데이터를 훈련 데이터로 하여 모델을 학습함으로써 모르는 아이템에 대한 평갓값을 예측합니다.

토픽 모델을 사용하면 평갓값 행렬을 차원 압축함으로써 잠재적인 의미를 표현하는 정보를 취득해 추천에 사용합니다. 행렬 분해에서는 평갓값 행렬을 그 곱이 원래의 행렬을 최대한 재현하는 형태로 하여 사용자 행렬과 아이템 행렬로 분해합니다.

 분해된 행렬에서 얻은사용자 벡터와 아이템 벡터의 유사도 계산을 통해 임의의 아이템에 대한 예측 평갓값을 계산합니다. 또 분해에서 얻은사용자 벡터와 아이템 백터를 다른 알고리즘의 입력으로 사용하기도 합니다.

|주요특성|협조 필터링|내용기반 필터링|
|---|:---:|:---:|
|다양성|O|X|
|도메인 지식 취급 비용|O|X|
|콜드 스타트 문제에 대한 대응|X|?|
|사용자 수가 적은 서비스에서의 추천|X|O|
|커버리지 향상|X|O|
|아이템 특징활용|X|O|
|예측 정확도|O|?|

