---
title: "추천 시스템 스터디 Part1"
author: "Sangkon Han"
---

## 재현 가능한 데이터 분석

많은 데이터 분서가들은 "2024년 여름 트랜드는 무엇인가요?"라는 질문을 2023년 9월쯤에 받게 됩니다. 이 질문에 답변은 쉽지만, 어렵습니다. 2024년 여름 트랜드에 대한 하나의 거대한 합의가 이뤄진 시점이라면 잡지나, 특정 도메인 영역에 있는 전문가들에게 인터뷰를 통해서 쉽게 알아낼 수 있기 때문입니다. 반면, 그 인터뷰를 의사결정에 활용하는 과정에서 답변을 데이터로 뒷받침하기 위해선 전혀 다른 고민이 필요합니다. 

모든 일의 시작은 질문을 하는 것에서 출발하고, 질문에 대한 대답을 하나의 가설로 가정하고, 그 가설에 적합한 자료를 찾아야 합니다. 그리고 그 가설은 검증 가능해야 합니다. 혹자는 좋은 안목과 도메인에 대한 통찰이 필요하다고 할 수 있지만, 그러한 영역에서 현재의 우리가 끼어들 여지는 없습니다. 따라서, 현재 우리는 "검증 가능한 가설"을 기준으로 업무를 진행해야 합니다.

### "주어진 가설을 검증 할 수 있어야 한다"

모든 데이터 분석가들은 자신의 주장에 대해서 "검증 가능한 자료"와 "방법"을 제시해야 합니다. 어쩌면 이런 일은 AI 시대를 건너야 하는 모든 사람들의 숙명이 될지도 모릅니다.

- [예제01] 검증을 위해서 우리가 해야 하는 행동
    - 데이터 수집
        - 도메인 영역에서 가장 앞선 혹은 선행된 지표를 확인
    - 가설 검증
        - 검증해야 되는 대상을 정의
        - 검증방법을 결정
            - 1) 전문가 집단 조사
            - 2) 면담
    - 시각화를 통해서 자료 검토 및 수정
    - 보고서를 작성하여 의견을 전달 및 검토

- [유제01] "출생아수가 줄어들고 있습니다"를 검증하세요.
    - 데이터 수집
        - KOSIS(국가 통계 포털)
    - "출생아수가 줄어들고 있습니다"
        - 출생아수 => 태어나는 모든 아기
        - 줄어든다 => 시계열(특정 시점에서 특정 시점까지 기울기가 음수)
    - 시각화
        - 1) 단순 시각화
        - 2) 인터렉션
    - 전달
        - 줄어들고 있다(사실)
        - "OO에서는 출생아수가 다른 OO에 비해서 완만하다"(의견)

## 분석환경

데이터 분석은 엑셀로 가능합니다. 혹은 프린트해서 컴퍼스와 자를 가지고도 가능합니다. 그럼에도 불구하고 도구를 사용하는 것은 엑셀이나, 컴퍼스와 자에 비해서 훨씬 좋은 결과를 기대하고, 과정을 계획할 수 있기 때문입니다. 따라서 분석환경은 중요합니다.

일단, 전 세계적으로 가장 많은 분석가들이 채택하는 `R`에 대해서 간략하게 알아보겠습니다.

- [예제2] `R` 개발 환경은 어떻게 구성될까?
    - R(언어), RStudio(IDE), renv(환경)
        - `R`이 통계학에서 사용하는 좋은 패키지를 잔뜩 가지고 있음
        - `ggplot`이라고 하는 그래프 라이브러리도 있음
        - `dataframe`이라고 하는 나름의 데이터구조도 활용할 수 있음

- [유제2] `Python` 개발 환경은 어떻게 구성될까?
    - Python(언어), VSCode/Colab/PyCharm(IDE), venv(개발환경구성)
        - Python이 머신러닝/딥러닝에서 사용하는 좋은 라이브러리를 잔뜩 가지고 있음
        - matplotlib/seaborn/pyplot이라고 하는 그래프 라이브러리도 있음
        - List/Dict라고하는 나름의 좋은 데이터구조를 가지고 있음

- [연습1] Python 개발 환경은 어떻게 구성될까?
    - Python(언어), VSCode, venv(개발환경구성) => 예, 문제가 없어요!
        - Pandas라고하는 좋은 분석도구를 사용
    - Solve) 개발환경 구성
        - 1)Python, VSCode를 설치하세요.
        - 2)VSCode 실행 후에 `File > Open Folder`를 이용해서 작업 환경을 구성하세요
        - 3)VSCode에 필요한 확장 프로그램(Python, Jupyter)를 설치하세요.
        - 5)`View > Command Palette` > `Python: Create Envir...`
        - 6)`day01.ipynb`(확장자!)를 만들어서, 커널을 선택하세요.
        - 7)`print("Hello, World")` 실행 확인 하시면 됩니다.

- [연습2] 데이터 분석 폴더
    - 모든 데이터는 `data`에 두도록 하세요.
    - 만들어진 모든 산출물은 `output`에 두도록 하세요.
    - 첨부되어진 모든 파일은 `static` 또는 `files`등을 활용하세요.

- [연습3] 파이썬 패키지 설치
    - `pip`를 활용
        - pip list
        - pip freeze
        - pip install
    - `pip install pandas`
        - numpy>=1.23.2
        - python-dateutil>=2.8.2
        - pytz>=2020.1
        - tzdata>=2022.7
    - `pip install seaborn`
    - `pip install openpyxl`

### FAQ
- a) VSCode가 문제다!
    - VSCode가 "텍스트 편집기"
    - VSCode에 확장 프로그램을 설치해서, 마치 IDE인 것처럼 사용
- b) 저 파이썬이 이상해요!
    - 아나콘다(Anaconda), 여러분이 뭘 필요로 하는지 모르지만, 모든 걸 다 설치해두었음
    - 단, 아나콘다를 사용하실 경우 기존에 설치된 파이썬과 충돌이 나지 않도록 주의
- c) 이렇게 복잡하게 할 필요가 있나요?
    - 재현 가능!
    - 내가 복잡하더라도, 상대방이 편리하다면 복잡성을 받아들일 자세가 되어있음
